# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-10 23:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'running'), (3, 'error')], default=0, editable=False, verbose_name='status')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItineraryStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('method', models.PositiveSmallIntegerField(choices=[(0, 'walk'), (1, 'bus'), (2, 'car'), (3, 'tube')], default=0)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('index', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Itinerary Steps',
                'verbose_name': 'Itinerary Step',
                'ordering': ['index', 'created'],
            },
        ),
        migrations.CreateModel(
            name='PlaceOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('place_id', models.CharField(max_length=255)),
                ('is_hotel', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=13, verbose_name='latitude')),
                ('lng', models.DecimalField(decimal_places=10, max_digits=13, verbose_name='longitude')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('opens', models.CharField(blank=True, max_length=4)),
                ('closes', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('visitFor', models.PositiveIntegerField(default=30)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_preference', to='itineraries.Itinerary', verbose_name='itinerary preferences')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_preference', to='itineraries.PlaceOfInterest', verbose_name='place to visit preference')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Itinerary Preferences',
                'verbose_name': 'Itinerary Preference',
            },
        ),
        migrations.AddField(
            model_name='itinerarystep',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='itineraries.PlaceOfInterest', verbose_name='the destination place'),
        ),
        migrations.AddField(
            model_name='itinerarystep',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='itineraries.Itinerary', verbose_name='itinerary'),
        ),
        migrations.AddField(
            model_name='itinerarystep',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='itineraries.PlaceOfInterest', verbose_name='the origin place'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='endingPOI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ending_point_for_itinerary', to='itineraries.PlaceOfInterest'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='initialPOI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_point_for_itinerary', to='itineraries.PlaceOfInterest'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
