# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeofinterest',
            name='closes',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='placeofinterest',
            name='opens',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
