# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 18:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerarystep',
            options={'ordering': ['created'], 'verbose_name': 'Itinerary Step', 'verbose_name_plural': 'Itinerary Steps'},
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itinerarystep',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='itineraries.Itinerary', verbose_name='itinerary'),
        ),
    ]
