# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-31 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_preferences_must_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarystep',
            name='index',
            field=models.PositiveSmallIntegerField(default=32767),
        ),
    ]
