# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-05 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_auto_20170705_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerarystep',
            options={'ordering': ['index', 'created'], 'verbose_name': 'Itinerary Step', 'verbose_name_plural': 'Itinerary Steps'},
        ),
        migrations.AddField(
            model_name='itinerary',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'completed'), (2, 'running'), (3, 'error')], default=0, editable=False, verbose_name='status'),
        ),
    ]
