# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0003_auto_20170731_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'low'), (1, 'medium'), (2, 'high'), (3, 'top')], default=0),
        ),
    ]
