# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0004_preferences_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarystep',
            name='method',
            field=models.PositiveSmallIntegerField(choices=[(0, 'walk'), (1, 'bike'), (2, 'car'), (3, 'tube')], default=0),
        ),
    ]
