# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0005_auto_20170817_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='index',
            field=models.PositiveSmallIntegerField(default=32767),
        ),
    ]
