(define (problem itinerary-953adb38-fe19-43eb-81e5-ba41b4a6531c)
        (:domain touristinfo)
	(:objects kensington-palace the-british-library trafalgar-square-1 hyde-park london-eye big-ben millennium-bridge  - location tourist1 - tourist walk car bike transit - mode)
	(:init 
 		(at 480.0 (awake tourist1))
		(at 1140.0 (not (awake tourist1)))
		(at 600.0 (open kensington-palace))
		(at 1080.0 (not (open kensington-palace)))
		(at 558.0 (open the-british-library))
		(at 1200.0 (not (open the-british-library)))
		(at 0 (open trafalgar-square-1))
		(at 300.0 (open hyde-park))
		(at 1440.0 (not (open hyde-park)))
		(at 0 (open london-eye))
		(at 0 (open big-ben))
		(at 0 (open millennium-bridge))
		(at tourist1 kensington-palace)
		(path kensington-palace the-british-library)
		(path kensington-palace the-british-library)
		(path kensington-palace trafalgar-square-1)
		(path kensington-palace trafalgar-square-1)
		(path kensington-palace hyde-park)
		(path kensington-palace hyde-park)
		(path kensington-palace london-eye)
		(path kensington-palace london-eye)
		(path kensington-palace big-ben)
		(path kensington-palace big-ben)
		(path kensington-palace millennium-bridge)
		(path kensington-palace millennium-bridge)
		(path the-british-library kensington-palace)
		(path the-british-library kensington-palace)
		(path the-british-library trafalgar-square-1)
		(path the-british-library trafalgar-square-1)
		(path the-british-library hyde-park)
		(path the-british-library hyde-park)
		(path the-british-library london-eye)
		(path the-british-library london-eye)
		(path the-british-library big-ben)
		(path the-british-library big-ben)
		(path the-british-library millennium-bridge)
		(path the-british-library millennium-bridge)
		(path trafalgar-square-1 kensington-palace)
		(path trafalgar-square-1 kensington-palace)
		(path trafalgar-square-1 the-british-library)
		(path trafalgar-square-1 the-british-library)
		(path trafalgar-square-1 hyde-park)
		(path trafalgar-square-1 hyde-park)
		(path trafalgar-square-1 london-eye)
		(path trafalgar-square-1 london-eye)
		(path trafalgar-square-1 big-ben)
		(path trafalgar-square-1 big-ben)
		(path trafalgar-square-1 millennium-bridge)
		(path trafalgar-square-1 millennium-bridge)
		(path hyde-park kensington-palace)
		(path hyde-park kensington-palace)
		(path hyde-park the-british-library)
		(path hyde-park the-british-library)
		(path hyde-park trafalgar-square-1)
		(path hyde-park trafalgar-square-1)
		(path hyde-park london-eye)
		(path hyde-park london-eye)
		(path hyde-park big-ben)
		(path hyde-park big-ben)
		(path hyde-park millennium-bridge)
		(path hyde-park millennium-bridge)
		(path london-eye kensington-palace)
		(path london-eye kensington-palace)
		(path london-eye the-british-library)
		(path london-eye the-british-library)
		(path london-eye trafalgar-square-1)
		(path london-eye trafalgar-square-1)
		(path london-eye hyde-park)
		(path london-eye hyde-park)
		(path london-eye big-ben)
		(path london-eye big-ben)
		(path london-eye millennium-bridge)
		(path london-eye millennium-bridge)
		(path big-ben kensington-palace)
		(path big-ben kensington-palace)
		(path big-ben the-british-library)
		(path big-ben the-british-library)
		(path big-ben trafalgar-square-1)
		(path big-ben trafalgar-square-1)
		(path big-ben hyde-park)
		(path big-ben hyde-park)
		(path big-ben london-eye)
		(path big-ben london-eye)
		(path big-ben millennium-bridge)
		(path big-ben millennium-bridge)
		(path millennium-bridge kensington-palace)
		(path millennium-bridge kensington-palace)
		(path millennium-bridge the-british-library)
		(path millennium-bridge the-british-library)
		(path millennium-bridge trafalgar-square-1)
		(path millennium-bridge trafalgar-square-1)
		(path millennium-bridge hyde-park)
		(path millennium-bridge hyde-park)
		(path millennium-bridge london-eye)
		(path millennium-bridge london-eye)
		(path millennium-bridge big-ben)
		(path millennium-bridge big-ben)
		(=(traveltime walk kensington-palace the-british-library)70.5)
		(=(traveltime transit kensington-palace the-british-library)28.72)
		(=(traveltime walk kensington-palace trafalgar-square-1)53.37)
		(=(traveltime transit kensington-palace trafalgar-square-1)25.23)
		(=(traveltime walk kensington-palace hyde-park)10.8)
		(=(traveltime transit kensington-palace hyde-park)10.52)
		(=(traveltime walk kensington-palace london-eye)60.8)
		(=(traveltime transit kensington-palace london-eye)21.53)
		(=(traveltime walk kensington-palace big-ben)55.55)
		(=(traveltime transit kensington-palace big-ben)19.1)
		(=(traveltime walk kensington-palace millennium-bridge)83.0)
		(=(traveltime transit kensington-palace millennium-bridge)33.47)
		(=(traveltime walk the-british-library kensington-palace)71.8)
		(=(traveltime transit the-british-library kensington-palace)33.13)
		(=(traveltime walk the-british-library trafalgar-square-1)36.68)
		(=(traveltime transit the-british-library trafalgar-square-1)18.62)
		(=(traveltime walk the-british-library hyde-park)48.17)
		(=(traveltime transit the-british-library hyde-park)34.88)
		(=(traveltime walk the-british-library london-eye)49.95)
		(=(traveltime transit the-british-library london-eye)26.38)
		(=(traveltime walk the-british-library big-ben)46.88)
		(=(traveltime transit the-british-library big-ben)21.35)
		(=(traveltime walk the-british-library millennium-bridge)45.35)
		(=(traveltime transit the-british-library millennium-bridge)30.87)
		(=(traveltime walk trafalgar-square-1 kensington-palace)53.77)
		(=(traveltime transit trafalgar-square-1 kensington-palace)26.62)
		(=(traveltime walk trafalgar-square-1 the-british-library)37.32)
		(=(traveltime transit trafalgar-square-1 the-british-library)17.85)
		(=(traveltime walk trafalgar-square-1 hyde-park)25.7)
		(=(traveltime transit trafalgar-square-1 hyde-park)25.73)
		(=(traveltime walk trafalgar-square-1 london-eye)15.68)
		(=(traveltime transit trafalgar-square-1 london-eye)12.2)
		(=(traveltime walk trafalgar-square-1 big-ben)10.6)
		(=(traveltime transit trafalgar-square-1 big-ben)15.0)
		(=(traveltime walk trafalgar-square-1 millennium-bridge)28.72)
		(=(traveltime transit trafalgar-square-1 millennium-bridge)22.5)
		(=(traveltime walk hyde-park kensington-palace)11.13)
		(=(traveltime transit hyde-park kensington-palace)12.57)
		(=(traveltime walk hyde-park the-british-library)47.77)
		(=(traveltime transit hyde-park the-british-library)35.2)
		(=(traveltime walk hyde-park trafalgar-square-1)25.48)
		(=(traveltime transit hyde-park trafalgar-square-1)26.22)
		(=(traveltime walk hyde-park london-eye)32.92)
		(=(traveltime transit hyde-park london-eye)25.1)
		(=(traveltime walk hyde-park big-ben)27.67)
		(=(traveltime transit hyde-park big-ben)22.67)
		(=(traveltime walk hyde-park millennium-bridge)55.12)
		(=(traveltime transit hyde-park millennium-bridge)38.45)
		(=(traveltime walk london-eye kensington-palace)66.02)
		(=(traveltime transit london-eye kensington-palace)26.18)
		(=(traveltime walk london-eye the-british-library)50.8)
		(=(traveltime transit london-eye the-british-library)25.67)
		(=(traveltime walk london-eye trafalgar-square-1)16.65)
		(=(traveltime transit london-eye trafalgar-square-1)15.35)
		(=(traveltime walk london-eye hyde-park)37.95)
		(=(traveltime transit london-eye hyde-park)24.95)
		(=(traveltime walk london-eye big-ben)13.03)
		(=(traveltime transit london-eye big-ben)4.78)
		(=(traveltime walk london-eye millennium-bridge)25.03)
		(=(traveltime transit london-eye millennium-bridge)13.75)
		(=(traveltime walk big-ben kensington-palace)56.2)
		(=(traveltime transit big-ben kensington-palace)32.38)
		(=(traveltime walk big-ben the-british-library)47.93)
		(=(traveltime transit big-ben the-british-library)18.67)
		(=(traveltime walk big-ben trafalgar-square-1)11.1)
		(=(traveltime transit big-ben trafalgar-square-1)9.32)
		(=(traveltime walk big-ben hyde-park)28.13)
		(=(traveltime transit big-ben hyde-park)23.4)
		(=(traveltime walk big-ben london-eye)6.45)
		(=(traveltime transit big-ben london-eye)6.35)
		(=(traveltime walk big-ben millennium-bridge)31.57)
		(=(traveltime transit big-ben millennium-bridge)20.37)
		(=(traveltime walk millennium-bridge kensington-palace)83.77)
		(=(traveltime transit millennium-bridge kensington-palace)33.52)
		(=(traveltime walk millennium-bridge the-british-library)46.37)
		(=(traveltime transit millennium-bridge the-british-library)24.72)
		(=(traveltime walk millennium-bridge trafalgar-square-1)29.2)
		(=(traveltime transit millennium-bridge trafalgar-square-1)18.57)
		(=(traveltime walk millennium-bridge hyde-park)55.7)
		(=(traveltime transit millennium-bridge hyde-park)38.85)
		(=(traveltime walk millennium-bridge london-eye)25.27)
		(=(traveltime transit millennium-bridge london-eye)18.13)
		(=(traveltime walk millennium-bridge big-ben)34.67)
		(=(traveltime transit millennium-bridge big-ben)19.02)
		(=(visitfor kensington-palace tourist1)25)
		(=(visitfor the-british-library tourist1)30)
		(=(visitfor trafalgar-square-1 tourist1)30)
		(=(visitfor hyde-park tourist1)270)
		(=(visitfor london-eye tourist1)30)
		(=(visitfor big-ben tourist1)30)
		(=(visitfor millennium-bridge tourist1)30)
		(=(havelunchfor tourist1) 50)
		(at 800 (canhavelunch tourist1))
		(at 1000 (not (canhavelunch tourist1 )))
		
	)
	(:goal
		(and
			(at tourist1 hyde-park)
			(hadlunch tourist1)
		)
	)
	(:constraints
		(and
			(preference VisitKensingtonPalace (at end (visited tourist1 kensington-palace)))
			(preference VisitTheBritishLibrary (at end (visited tourist1 the-british-library)))
			(preference VisitTrafalgarSquare1 (at end (visited tourist1 trafalgar-square-1)))
			(preference VisitHydePark (at end (visited tourist1 hyde-park)))
			(preference VisitLondonEye (at end (visited tourist1 london-eye)))
			(preference VisitBigBen (at end (visited tourist1 big-ben)))
			(preference VisitMillenniumBridge (at end (visited tourist1 millennium-bridge)))
			
		)
	)
	(:metric minimize
		;(+
			;(total-time)
			(* 100 (+
					(is-violated VisitMillenniumBridge)
					(is-violated VisitBigBen)
					(is-violated VisitLondonEye)
					(is-violated VisitHydePark)
					(is-violated VisitTrafalgarSquare1)
					(is-violated VisitTheBritishLibrary)
					(is-violated VisitKensingtonPalace)
 ) );)
		
	)
)