(define (problem itinerary-3192b58c-833b-4c1e-ab07-dda8e6a7cac8)
        (:domain touristinfo) 
	(:objects big-ben leicester-square-station waterstones-london-piccadilly chelsea da-mario strand  - location tourist1 - tourist bus walk - mode)
 	(:init 
 		(at 0 (open big-ben))
		(at 0 (open leicester-square-station))
		(at 0 (open waterstones-london-piccadilly))
		(at 0 (open chelsea))
		(at 0 (open da-mario))
		(at 0 (open strand))
 		(at tourist1 big-ben)
 		(path big-ben leicester-square-station)
		(path big-ben waterstones-london-piccadilly)
		(path big-ben chelsea)
		(path big-ben da-mario)
		(path big-ben strand)
		(path leicester-square-station big-ben)
		(path leicester-square-station waterstones-london-piccadilly)
		(path leicester-square-station chelsea)
		(path leicester-square-station da-mario)
		(path leicester-square-station strand)
		(path waterstones-london-piccadilly big-ben)
		(path waterstones-london-piccadilly leicester-square-station)
		(path waterstones-london-piccadilly chelsea)
		(path waterstones-london-piccadilly da-mario)
		(path waterstones-london-piccadilly strand)
		(path chelsea big-ben)
		(path chelsea leicester-square-station)
		(path chelsea waterstones-london-piccadilly)
		(path chelsea da-mario)
		(path chelsea strand)
		(path da-mario big-ben)
		(path da-mario leicester-square-station)
		(path da-mario waterstones-london-piccadilly)
		(path da-mario chelsea)
		(path da-mario strand)
		(path strand big-ben)
		(path strand leicester-square-station)
		(path strand waterstones-london-piccadilly)
		(path strand chelsea)
		(path strand da-mario)
 		(=(traveltime walk big-ben leicester-square-station)16.78)
		(=(traveltime walk big-ben waterstones-london-piccadilly)20.2)
		(=(traveltime walk big-ben chelsea)52.42)
		(=(traveltime walk big-ben da-mario)58.23)
		(=(traveltime walk big-ben strand)19.4)
		(=(traveltime walk leicester-square-station big-ben)15.52)
		(=(traveltime walk leicester-square-station waterstones-london-piccadilly)8.03)
		(=(traveltime walk leicester-square-station chelsea)61.1)
		(=(traveltime walk leicester-square-station da-mario)56.72)
		(=(traveltime walk leicester-square-station strand)9.32)
		(=(traveltime walk waterstones-london-piccadilly big-ben)18.83)
		(=(traveltime walk waterstones-london-piccadilly leicester-square-station)7.95)
		(=(traveltime walk waterstones-london-piccadilly chelsea)54.92)
		(=(traveltime walk waterstones-london-piccadilly da-mario)48.92)
		(=(traveltime walk waterstones-london-piccadilly strand)17.13)
		(=(traveltime walk chelsea big-ben)52.77)
		(=(traveltime walk chelsea leicester-square-station)62.35)
		(=(traveltime walk chelsea waterstones-london-piccadilly)56.57)
		(=(traveltime walk chelsea da-mario)22.67)
		(=(traveltime walk chelsea strand)65.43)
		(=(traveltime walk da-mario big-ben)58.32)
		(=(traveltime walk da-mario leicester-square-station)57.85)
		(=(traveltime walk da-mario waterstones-london-piccadilly)50.13)
		(=(traveltime walk da-mario chelsea)22.18)
		(=(traveltime walk da-mario strand)66.68)
		(=(traveltime walk strand big-ben)18.25)
		(=(traveltime walk strand leicester-square-station)9.43)
		(=(traveltime walk strand waterstones-london-piccadilly)17.38)
		(=(traveltime walk strand chelsea)63.83)
		(=(traveltime walk strand da-mario)65.6)
 		(=(visitfor big-ben tourist1)19)
		(=(visitfor leicester-square-station tourist1)79)
		(=(visitfor waterstones-london-piccadilly tourist1)75)
		(=(visitfor chelsea tourist1)69)
		(=(visitfor da-mario tourist1)95)
		(=(visitfor strand tourist1)56)
	)
 	(:goal
		(and
			(at tourist1 big-ben)
			(preference VisitBigBen (visited tourist1 big-ben))
			(preference VisitLeicesterSquareStation (visited tourist1 leicester-square-station))
			(preference VisitWaterstonesLondonPiccadilly (visited tourist1 waterstones-london-piccadilly))
			(preference VisitChelsea (visited tourist1 chelsea))
			(preference VisitDaMario (visited tourist1 da-mario))
			(preference VisitStrand (visited tourist1 strand))
		)
	)
 	(:constraints
		(and
			(preference VisitBigBen (at end (visited tourist1 big-ben)))
			(preference VisitLeicesterSquareStation (at end (visited tourist1 leicester-square-station)))
			(preference VisitWaterstonesLondonPiccadilly (at end (visited tourist1 waterstones-london-piccadilly)))
			(preference VisitChelsea (at end (visited tourist1 chelsea)))
			(preference VisitDaMario (at end (visited tourist1 da-mario)))
			(preference VisitStrand (at end (visited tourist1 strand)))
		)
	) 
	(:metric minimize
		(+
			(total-time)
			(* 1000    
				(+
					(is-violated VisitBigBen)
					(is-violated VisitLeicesterSquareStation)
					(is-violated VisitWaterstonesLondonPiccadilly)
					(is-violated VisitChelsea)
					(is-violated VisitDaMario)
					(is-violated VisitStrand)
				)
			)
		)
	)
)
