(define (problem itinerary-e2b21b76-d39c-4e73-89b7-13215320b6d2)
        (:domain touristinfo) 
	(:objects maughan-library franco-manca fat-face-ltd  - location tourist1 - tourist bus walk - mode)
 	(:init 
 		(at 1000 (open maughan-library))
		(at 0100 (not (open maughan-library)))
		(at 1200 (open franco-manca))
		(at 2300 (not (open franco-manca)))
		(at 0900 (open fat-face-ltd))
		(at 1800 (not (open fat-face-ltd)))
 		(at tourist1 franco-manca)
 		(path maughan-library franco-manca)
		(path maughan-library fat-face-ltd)
		(path franco-manca maughan-library)
		(path franco-manca fat-face-ltd)
		(path fat-face-ltd maughan-library)
		(path fat-face-ltd franco-manca)
 		(=(traveltime walk maughan-library franco-manca)14.22)
		(=(traveltime walk maughan-library fat-face-ltd)30.5)
		(=(traveltime walk franco-manca maughan-library)14.55)
		(=(traveltime walk franco-manca fat-face-ltd)30.67)
		(=(traveltime walk fat-face-ltd maughan-library)30.58)
		(=(traveltime walk fat-face-ltd franco-manca)31.05)
 		(=(visitfor maughan-library tourist1)68)
		(=(visitfor franco-manca tourist1)56)
		(=(visitfor fat-face-ltd tourist1)49)
	)
 	(:goal
		(and
			(at tourist1 franco-manca)
			(preference VisitMaughanLibrary (visited tourist1 maughan-library))
			(preference VisitFrancoManca (visited tourist1 franco-manca))
			(preference VisitFatFaceLtd (visited tourist1 fat-face-ltd))
		)
	)
 	(:constraints
		(and
			(preference VisitMaughanLibrary (at end (visited tourist1 maughan-library)))
			(preference VisitFrancoManca (at end (visited tourist1 franco-manca)))
			(preference VisitFatFaceLtd (at end (visited tourist1 fat-face-ltd)))
		)
	) 
	(:metric minimize
		(+
			(total-time)
			(* 1000    
				(+
					(is-violated VisitMaughanLibrary)
					(is-violated VisitFrancoManca)
					(is-violated VisitFatFaceLtd)
				)
			)
		)
	)
)
