(define (problem itinerary-45881689-f16f-46de-8ec7-71b57b1d44ad)
        (:domain touristinfo) 
	(:objects maughan-library franco-manca temple-station  - location tourist1 - tourist bus walk - mode)
 	(:init 
 		(at 1000 (open maughan-library))
		(at 0100 (not (open maughan-library)))
		(at 1200 (open franco-manca))
		(at 2300 (not (open franco-manca)))
		(at 0 (open temple-station))
		(at 0 (not (open temple-station)))
 		(at tourist1 franco-manca)
 		(path maughan-library franco-manca)
		(path maughan-library temple-station)
		(path franco-manca maughan-library)
		(path franco-manca temple-station)
		(path temple-station maughan-library)
		(path temple-station franco-manca)
 		(=(traveltime walk maughan-library franco-manca)14.22)
		(=(traveltime walk maughan-library temple-station)7.45)
		(=(traveltime walk franco-manca maughan-library)14.55)
		(=(traveltime walk franco-manca temple-station)10.05)
		(=(traveltime walk temple-station maughan-library)8.35)
		(=(traveltime walk temple-station franco-manca)10.6)
 		(=(visitfor maughan-library tourist1)105)
		(=(visitfor franco-manca tourist1)32)
		(=(visitfor temple-station tourist1)81)
	)
 	(:goal
		(and
			(at tourist1 franco-manca)
			(preference VisitMaughanLibrary (visited tourist1 maughan-library))
			(preference VisitFrancoManca (visited tourist1 franco-manca))
			(preference VisitTempleStation (visited tourist1 temple-station))
		)
	)
 	(:constraints
		(and
			(preference VisitMaughanLibrary (at end (visited tourist1 maughan-library)))
			(preference VisitFrancoManca (at end (visited tourist1 franco-manca)))
			(preference VisitTempleStation (at end (visited tourist1 temple-station)))
		)
	) 
	(:metric minimize
		(+
			(total-time)
			(* 1000    
				(+
					(is-violated VisitMaughanLibrary)
					(is-violated VisitFrancoManca)
					(is-violated VisitTempleStation)
				)
			)
		)
	)
)
